### ISSUE TITLE
Requested but not Supported by System (L2/MBA)

### ISSUE THREAD

**Issue by shelbyt** [intel/intel-cmt-cat#44] opened 2017-04-12 16:51 UTC
Having trouble using CAT with the L2.

System Information:
**[uname -R]**
4.10.0-041000-generic

**[cpuinfo]**
processor       : 47
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
stepping        : 1

**[/etc/os-release]**
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian

When using pqos to do L2 or MBA allocation 
`sudo pqos -e l2:2=0x1`
 I get this error:

Socket 0 MBA COS1 - FAILED!
Allocation configuration error!

L2ID 0 L2CA COS2 - FAILED!
Allocation configuration error!

Tried same thing with RDTSET
`sudo rdtset -t 'l2=0xf;cpu=2' -c 2 sleep 10`

got this error:
Allocation: L2CA requested but not supported by system!
Requested configuration is not valid!
Allocation: Failed to configure allocation!

Tried with resctrl 
`echo "L2:0=1;1=1" > COS1/schemata`
error: bash: echo: write error: Invalid argument

I am able to do L3 +CAT using all three methods but L2 and MBA allocation are erroring out. Am I allocating these incorrectly? Thanks.

**Comment by ahetheri** [comment] 2017-04-12 17:04
Hi shelbyt,

Thanks for getting in touch.
Unfortunately the error message you are receiving is correct.
Allocation: L2CA requested but not supported by system!

Your Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz does not support L2 or MBA CAT.
It does support L3 CAT and CDP.

Sorry about this.

Best,
Aaron

**Comment by shelbyt** [comment] 2017-04-12 17:11
Thanks for the fast response Aaron. Where can I find what capabilities are supported by which processor? The main wiki for CMT says that CAT is supported by E5 v4 but not which models specifically.

**Comment by ahetheri** [comment] 2017-04-12 19:48
Hi shelbyt,

I have just read the wiki and have seen it has not been updated for L2!
Apologies for this, we will fix this ASAP.

To answer your question the Intel (R) Atom C3000 series support L2 CAT
https://ark.intel.com/products/series/97941/Intel-Atom-Processor-C3000-Product-Family?q=atom%20c300

As for MBA, no current system is available with MBA CAT.
We programmed how to do it based on specifications found in the software developers manual:
https://software.intel.com/en-us/articles/intel-sdm

I hope this helps clear things up,
Let me know if I can provide any more information.

Best,
Aaron

**Comment by tkanteck** [comment] 2017-04-18 10:17
"To clarify, L3 CMT, L3 CAT, MBM and CDP is available on all Intel (R) Xeon E5 v4 products." - and Intel(R) Xeon(R) E7 v4 porducts, too.

**Comment by PennPanda** [comment] 2017-06-27 13:49
Hi @ahetheri ,

I'm just wondering if you found which systems on ark.intel.com support MBA?

Thanks,

Meng

**Comment by shelbyt** [comment] 2017-06-27 15:53
@PennPanda MBA will be present in Skylake servers according to Fenghua Yu

**Comment by ahetheri** [comment] 2017-06-27 16:06
Hi @shelbyt 

Can you point to the location where Fenghua provided this information please?

Best,
Aaron

**Comment by shelbyt** [comment] 2017-06-27 16:24
@ahetheri  Talked with him over email.

**Comment by tkanteck** [comment] 2017-06-27 21:46
Since the above information comes from private conversation and it is not confirmed via any other sources I have no choice but delete the above responses.

**Comment by mdcornu** [comment] 2018-05-03 12:39
Closing this issue. Please reopen if needed.

Regards,
Marcel

**Closed by mdcornu** 2018-05-03 12:39 UTC

**Comment by Jeongseob** [comment] 2018-05-10 12:55
Can anyone give me the information about which specific model supports MBA?

**Comment by mdcornu** [comment] 2018-05-10 16:01
Please refer to the [Intel(R) RDT hardware support](https://github.com/intel/intel-cmt-cat/blob/c86fb085a093fe22bea31dfce0c94df09104e828/README#L112) table in our README which outlines features that are supported on specific models.

Regards,
Marcel

**Comment by mdcornu** [comment] 2018-05-21 09:40
Hi Jeongseob,

Apologies for the delayed response.
All Intel(R) Xeon(R) Scalable Processors Bronze/Silver/Gold support MBA.

**Note:**
Please find errata for Intel(R) Xeon(R) Processor Scalable Family at:
https://www.intel.com/content/dam/www/public/us/en/documents/specification-updates/xeon-scalable-spec-update.pdf?asset=14615

Regards,
Marcel
