### ISSUE TITLE
pqos -IMonitoring start error on core(s) 0, status 2

### ISSUE THREAD

**Issue by RERV** [intel/intel-cmt-cat#123] opened 2019-09-29 10:13 UTC

**Comment by RERV** [comment] 2019-09-29 10:18
I’m sorry I was new to rdt. 
When I try to use "pqos -I", it said Monitoring start error on core(s) 0, status 2.
![image](https://user-images.githubusercontent.com/39251602/65830779-379dfe00-e2e5-11e9-84ab-34485554260c.png)


The vision of my kernel is 4.14.146
And the cpu is Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz
![image](https://user-images.githubusercontent.com/39251602/65830795-5e5c3480-e2e5-11e9-88b0-ee10d084090d.png)

**Comment by kmabbasi** [comment] 2019-09-30 15:39
Hi,
Could you please try 'pqos -r' first?

Thanks,
Khawar

**Comment by RERV** [comment] 2019-10-02 03:04
Hi，
I tried it and it shows
![image](https://user-images.githubusercontent.com/39251602/66015242-5fb77800-e504-11e9-9272-4277837caf2f.png)
Thanks.

**Comment by RERV** [comment] 2019-10-02 03:07
And when I try pqos -s -V，it said:
![image](https://user-images.githubusercontent.com/39251602/66015324-adcc7b80-e504-11e9-89bf-b42e19d09db7.png)
![image](https://user-images.githubusercontent.com/39251602/66015335-b755e380-e504-11e9-88fa-20faa245b9d3.png)
![image](https://user-images.githubusercontent.com/39251602/66015349-cb99e080-e504-11e9-8975-f4ce8a455525.png)
![image](https://user-images.githubusercontent.com/39251602/66015367-d81e3900-e504-11e9-99f2-d8f7c3fe95c2.png)

**Comment by kmabbasi** [comment] 2019-10-02 12:33
Thanks for sharing screenshots. It looks it is working. 

Thanks,
Khawar

**Comment by RERV** [comment] 2019-10-02 12:46
However, when I try to use "-I", almost all wrong.
![image](https://user-images.githubusercontent.com/39251602/66044968-50ace600-e555-11e9-8af3-a9a1e8a6eea1.png)
I don't know what happened.
Thanks.

**Comment by kmabbasi** [comment] 2019-10-03 10:10
Could you please try core monitoring using 'pqos -I'? 
Perhaps the PID '14453' has died between detecting top pids and started monitoring. Try rerunning the original command again.

Thanks,
Khawar

**Comment by RERV** [comment] 2019-10-03 10:14
I'm sorry it seems not work.
![image](https://user-images.githubusercontent.com/39251602/66118662-8ca18300-e609-11e9-9be1-fbebcb9f3179.png)
![image](https://user-images.githubusercontent.com/39251602/66118691-9b883580-e609-11e9-84ef-f70026ffe07b.png)
Thanks.

**Comment by kmabbasi** [comment] 2019-10-03 12:28
Just to cross check could you please try 'pqos -Ir' and send the output?

**Comment by RERV** [comment] 2019-10-04 08:33
![image](https://user-images.githubusercontent.com/39251602/66193171-9b993b80-e6c4-11e9-9486-74970d4463ec.png)

**Comment by kmabbasi** [comment] 2019-10-04 13:36
Can you please provide more details which can help us to reproduce it? details such as Pqos version, linux kernel version, OS, whether you are running this on host/bare-metal platform or guest/virtualized environment (K8s, hypervisor, etc.)

Thanks,
Khawar

**Comment by kmabbasi** [comment] 2019-10-25 11:25
Since we didn't hear anything back from you from last 3 weeks, it looks your issue has been resolved. Therefore, going to close this issue now. 

Thanks,
Khawar

**Closed by kmabbasi** 2019-10-25 11:25 UTC
